import type { TodayRecommendation } from "@tm/shared";
import { listExecutionContexts } from "../contexts/repo";
import { buildTodayOverview } from "../today/overview";
import { getRawSettings, markSent } from "./repo";
import { esc, sendSesEmail } from "./ses";

type Group = { contextName: string; recommendations: TodayRecommendation[] };

function taskLine(r: TodayRecommendation): string {
  const t = r.task;
  const bits = [r.project?.title ? `Project: ${r.project.title}` : undefined, t.dueDate ? `Due: ${t.dueDate}` : undefined, t.priority ? `P${t.priority}` : undefined].filter(Boolean).join(" · ");
  return `${t.title}${bits ? ` (${bits})` : ""}`;
}

function render(groups: Group[]) {
  const text = groups.map((g) => [`${g.contextName}:`, ...(g.recommendations.length ? g.recommendations.map((r, i) => `${i + 1}. ${taskLine(r)}`) : ["No matching recommended tasks."]), ""].join("\n")).join("\n");
  const html = `<div style="font-family:Arial,sans-serif;line-height:1.45"><h2>Execution Guidance recommendations</h2>${groups.map((g) => `<h3>${esc(g.contextName)}</h3>${g.recommendations.length ? `<ol>${g.recommendations.map((r) => `<li><strong>${esc(r.task.title)}</strong>${r.project?.title ? `<br><span>Project: ${esc(r.project.title)}</span>` : ""}${r.task.dueDate ? `<br><span>Due: ${esc(r.task.dueDate)}</span>` : ""}${r.task.priority ? `<br><span>Priority: P${r.task.priority}</span>` : ""}</li>`).join("")}</ol>` : `<p>No matching recommended tasks.</p>`}`).join("")}<p style="color:#666;font-size:12px">Generated by Execution Guidance System.</p></div>`;
  return { text, html };
}

export async function sendRecommendationsEmailForUser(sub: string, now = new Date()): Promise<{ sent: boolean; message: string; sentAt?: string }> {
  const [raw, contexts] = await Promise.all([getRawSettings(sub), listExecutionContexts(sub)]);
  const notificationEmail = typeof raw?.notificationEmail === "string" ? raw.notificationEmail.trim() : "";
  if (!notificationEmail) return { sent: false, message: "Notification email address is not configured." };

  const topN = Math.max(1, Math.min(20, Number(raw?.notificationSchedule?.topN || 5)));
  const significant = contexts.filter((c) => c.significant && !c.archived);
  if (!significant.length) return { sent: false, message: "No significant execution contexts are selected." };

  const groups: Group[] = [];
  for (const context of significant) {
    const overview = await buildTodayOverview(sub, false, now, [context.contextId], false);
    groups.push({ contextName: context.name, recommendations: overview.recommended.slice(0, topN) });
  }
  const { html, text } = render(groups);
  await sendSesEmail(notificationEmail, `EGS recommendations - ${now.toLocaleDateString("en-AU")}`, html, text);
  await markSent(sub, now);
  return { sent: true, message: "Recommendation email sent.", sentAt: now.toISOString() };
}
